import { PrivacyPolicyCopy } from '../privacy-policy.types';

const privacyPolicyEn: PrivacyPolicyCopy = {
  meta: {
    title: 'Privacy Policy - BeMyTeamMate',
    description:
      'The BeMyTeamMate privacy policy, including the scope of processed data, legal basis, processors, and data subject rights.',
  },
  html: `
    <header class="privacy-header">
      <h1>Privacy Policy</h1>
      <div class="privacy-divider" role="presentation"></div>
    </header>

    <div class="privacy-content">
      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">1.</span>
          <h2>Controller details</h2>
        </div>
        <p>Data controller (hereinafter: Controller):</p>
        <ul>
          <li><strong>Name: </strong> Be My Team Mate</li>
          <li>
            <strong>Email: </strong>
            <a class="privacy-link select-none" href="mailto:__CONTACT_EMAIL__">__CONTACT_EMAIL__</a>
          </li>
          <li>
            <strong>Website: </strong>
            <a class="privacy-link" href="https://bemyteammate.eu" target="_blank" rel="noreferrer">
              https://bemyteammate.eu
            </a>
          </li>
        </ul>
        <p>
          The Controller processes the personal data of website visitors and registered users under the terms described
          in this notice.
        </p>
      </section>

      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">2.</span>
          <h2>Legal background</h2>
        </div>
        <p>
          The Controller processes personal data in accordance with Regulation (EU) 2016/679 of the European
          Parliament and of the Council (GDPR) and Act CXII of 2011 (Infotv.).
        </p>
        <p>
          We are committed to respecting visitors' informational self-determination rights. We keep data confidential
          and take all necessary technical and organizational measures to ensure security.
        </p>
      </section>

      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">3.</span>
          <h2>Data processing principles</h2>
        </div>
        <p>The Controller processes personal data:</p>
        <ul>
          <li>lawfully, fairly, and transparently,</li>
          <li>for specified, explicit, and legitimate purposes,</li>
          <li>not in a manner incompatible with those purposes,</li>
          <li>only to the extent necessary and relevant to the processing purpose (data minimization),</li>
          <li>for no longer than necessary (storage limitation),</li>
          <li>with appropriate technical and organizational measures.</li>
        </ul>
      </section>

      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">4.</span>
          <h2>Scope, purpose and legal basis of the personal data processed</h2>
        </div>
        <p>
          Without registration, the website does not collect personal data that could directly identify a visitor,
          except for technical logs and cookies (see 4.2. and 4.3.).
        </p>

        <div class="privacy-subsection">
          <h3>4.1. Registration and account data</h3>
          <p><strong>Scope of processed data:</strong></p>
          <ul>
            <li>Email address: the email address provided by the user during registration and login,</li>
            <li>Username: the name chosen by the user and shown in the system,</li>
            <li>Firebase identifier: the unique user identifier automatically generated by Firebase Authentication,</li>
            <li>Role: the user permission level,</li>
            <li>Last login timestamp: the timestamp of the user's most recent successful login.</li>
          </ul>
          <p><br /><strong>Purpose of processing:</strong></p>
          <ul>
            <li>creating and operating a user account,</li>
            <li>providing login and authentication,</li>
            <li>permission management (for example, controlling access to admin functions),</li>
            <li>tracking the technical operation of the system,</li>
            <li>detecting and preventing security issues, abuse and unauthorized access,</li>
            <li>identifying and managing inactive user accounts,</li>
            <li>administrative tracking of user account activity.</li>
          </ul>
          <p><br /><strong>Legal basis:</strong></p>
          <ul>
            <li>GDPR Article 6(1)(b) - performance of a contract: registration is required to use the service and processing is necessary for account operation,</li>
            <li>GDPR Article 6(1)(f) - legitimate interest: the Controller's legitimate interest is to operate the service securely and transparently and prevent abuse.</li>
          </ul>
          <p><br /><strong>Retention period:</strong></p>
          <ul>
            <li>for as long as the user account exists, or until deletion,</li>
            <li>the user may request deletion of the account and related personal data at any time from the user profile settings or through the Controller's contact details.</li>
          </ul>
        </div>

        <div class="privacy-subsection">
          <h3>4.2. Technical data from Firebase services</h3>
          <p>
            The website uses Firebase (Google Cloud Platform) for data storage, authentication, and backend
            functionality. Firebase may automatically record certain technical data to ensure service operation and
            security.
          </p>
          <p><br /><strong>Purpose of processing:</strong></p>
          <ul>
            <li>ensuring the technical operation of the website,</li>
            <li>user authentication and account management,</li>
            <li>data storage and database services,</li>
            <li>maintaining the security of the IT system.</li>
          </ul>
          <p><br /><strong>Processor:</strong></p>
          <ul>
            <li><strong>Name:</strong> Google LLC (Firebase / Google Cloud Platform)</li>
            <li><strong>Seat:</strong> 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA</li>
            <li>
              <strong>More information:</strong>
              <a class="privacy-link" href="https://firebase.google.com/support/privacy" target="_blank" rel="noreferrer">
                https://firebase.google.com/support/privacy
              </a>
            </li>
          </ul>
          <p><br /><strong>DPA and data transfer:</strong></p>
          <p>
            Google LLC acts as a processor for Firebase/Google Cloud Platform services. The data processing agreement
            between the Controller and Google is part of the Google Workspace / Cloud / Firebase terms.
          </p>
          <p><br /><strong>Transfer destination:</strong> The data is transferred to the United States (USA).</p>
          <p><br /><strong>Legal basis and safeguards:</strong></p>
          <ul>
            <li>EU-US Data Privacy Framework: Google LLC participates in the EU-US Data Privacy Framework, which provides a compliance mechanism for transfers.</li>
            <li>Standard Contractual Clauses (SCC): Google applies the European Commission approved standard contractual clauses with additional safeguards.</li>
            <li>Additional technical and organizational measures: Google uses further security measures such as encryption and access restrictions.</li>
          </ul>
          <br />
          <p>
            More information about the data processing agreement and Google privacy practices:
            <a class="privacy-link" href="https://cloud.google.com/terms/data-processing-addendum" target="_blank" rel="noreferrer">
              Google Cloud Data Processing Addendum
            </a>
          </p>
        </div>

        <div class="privacy-subsection">
          <h3>4.3. Cookies and Google Analytics</h3>
          <p>
            We use Google Analytics to measure traffic and site usage. The service places cookies on the user's device
            and collects anonymous statistical data.
          </p>
          <p><br /><strong>Scope of data processed:</strong></p>
          <ul>
            <li>browser and device type,</li>
            <li>IP address (with IP anonymization),</li>
            <li>geographic location (city level),</li>
            <li>session identifier,</li>
            <li>time and duration of the visit,</li>
            <li>visited pages and clicks.</li>
          </ul>
          <br />
          <p>
            The data collected by Google Analytics does not directly identify the visitor, but under the GDPR it may
            still qualify as personal data, especially the IP address and unique identifiers.
          </p>
          <p><br /><strong>Purpose of processing:</strong></p>
          <ul>
            <li>analyzing website usage,</li>
            <li>creating traffic statistics,</li>
            <li>improving the service.</li>
          </ul>
          <p><br /><strong>Legal basis:</strong> consent</p>
          <p>The legal basis for Google Analytics cookies is consent under GDPR Article 6(1)(a).</p>
          <p>
            The user consents to cookies and Google Analytics through the cookie banner on the website. Consent may be
            withdrawn at any time by changing browser cookie settings or reopening the cookie banner settings.
          </p>
          <p><br /><strong>IP anonymization and settings:</strong></p>
          <ul>
            <li>IP anonymization is enabled.</li>
            <li>The data collected by Google Analytics does not directly identify the visitor.</li>
            <li>The cookie retention period is the applicable data storage period (up to 2 years).</li>
            <li>If you do not want to share data, you can disable Google Analytics with a browser extension or delete cookies in your browser.</li>
          </ul>
          <p><br /><strong>Data transfer to the United States</strong></p>
          <p>
            Google Analytics is provided by Google LLC (1600 Amphitheatre Parkway, Mountain View, CA 94043, USA).
            Information collected via cookies may primarily be transferred to servers located in the United States.
          </p>
          <br />
          <p>
            Several European data protection authorities have considered the current Google Analytics practice
            problematic because transfer to a third country requires additional technical and organizational safeguards.
            The Controller aims to provide the strongest possible protection by using the available settings and legal
            safeguards such as IP anonymization and contractual guarantees.
          </p>
        </div>

        <div class="privacy-subsection">
          <h3>4.4. Cloudflare services (Website hosting and security)</h3>
          <p>
            The website uses Cloudflare services for content delivery (hosting), security hardening, and abuse
            prevention such as bot protection. Cloudflare may collect cookies and technical data to keep the site
            secure and fast.
          </p>
          <p><br /><strong>Scope of data processed:</strong></p>
          <ul>
            <li>IP address,</li>
            <li>browser and device data,</li>
            <li>technical log files related to website visits,</li>
            <li>Turnstile CAPTCHA data: analysis of user interactions in bot protection.</li>
          </ul>
          <p><br /><strong>Purpose of processing:</strong></p>
          <ul>
            <li>serving the website (Cloudflare Pages),</li>
            <li>detecting and preventing security threats such as DDoS attacks and bots,</li>
            <li>ensuring fast and uninterrupted content delivery (CDN service).</li>
          </ul>
          <p><br /><strong>Processor:</strong></p>
          <ul>
            <li><strong>Name:</strong> Cloudflare, Inc.</li>
            <li><strong>Seat:</strong> 101 Townsend St, San Francisco, CA 94107, USA</li>
            <li>
              <strong>More information:</strong>
              <a class="privacy-link" href="https://www.cloudflare.com/trust-hub/privacy-and-data-protection/" target="_blank" rel="noreferrer">
                https://www.cloudflare.com/trust-hub/privacy-and-data-protection/
              </a>
            </li>
          </ul>
          <p><br /><strong>Legal basis and transfers:</strong></p>
          <ul>
            <li>Legitimate interest (GDPR Article 6(1)(f)): secure operation of the website and defense against attacks.</li>
            <li>Transfers: Cloudflare operates a global network, so data may be transferred to the USA or other countries under appropriate safeguards such as SCCs.</li>
          </ul>
        </div>
      </section>

      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">5.</span>
          <h2>Processors</h2>
        </div>
        <p>The Controller may use the following processors in the course of data processing:</p>
        <ul>
          <li><strong>Website hosting provider:</strong> Cloudflare, Inc. (San Francisco, USA) - website hosting and static asset storage.</li>
          <li><strong>Data storage and authentication:</strong> Google LLC (Firebase / Google Cloud Platform) - user data is stored in Firebase, which protects data with appropriate technical and organizational measures.</li>
          <li><strong>Analytics provider:</strong> Google LLC - Google Analytics (see above).</li>
          <li><strong>Security provider (CAPTCHA):</strong> Cloudflare, Inc. - Cloudflare Turnstile bot protection.</li>
        </ul>
        <p>
          The Controller transfers personal data to third parties only for the purposes specified in this notice and
          with proper information provided to the data subject.
        </p>
      </section>

      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">6.</span>
          <h2>Retention periods</h2>
        </div>
        <ul>
          <li>Last login timestamp: for as long as the account exists / until deletion,</li>
          <li>Google Analytics cookies: until cookie expiry (up to 2 years), or until deleted by the browser.</li>
        </ul>
        <p>Once the retention period expires, personal data is deleted or anonymized.</p>
      </section>

      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">7.</span>
          <h2>Rights of data subjects</h2>
        </div>
        <p>Under the GDPR, the data subject (website visitor or user) has the following rights:</p>
        <ul>
          <li>Right of access - you may request information on whether the Controller processes your personal data, and if so, which data, for what purpose, on what legal basis, and for how long.</li>
          <li>Right to rectification - you may request correction or completion of inaccurate or incomplete data.</li>
          <li>Right to erasure ("right to be forgotten") - in certain cases you may request deletion of your personal data.</li>
          <li>Right to restriction of processing - you may request that processing be restricted (for example if data accuracy is disputed).</li>
          <li>Right to data portability - in certain cases you may request that the Controller provide your data in a machine-readable format or transmit it to another controller.</li>
          <li>Right to object - you may object to processing based on legitimate interest.</li>
        </ul>
        <p>You may submit a request to exercise your rights at the following contact:</p>
        <p>
          <strong>Email: </strong>
          <a class="privacy-link select-none" href="mailto:__CONTACT_EMAIL__">__CONTACT_EMAIL__</a>
        </p>
        <p>
          The Controller will inform the data subject of the measures taken within 1 month of receiving the request at
          the latest.
        </p>
      </section>

      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">8.</span>
          <h2>Legal remedies</h2>
        </div>
        <p>
          If the data subject believes that the processing of personal data violates the GDPR, the following options
          are available:
        </p>
        <div class="privacy-subsection">
          <h3>1. File a complaint with the supervisory authority:</h3>
          <p><strong>National Authority for Data Protection and Freedom of Information (NAIH)</strong></p>
          <p>Seat: 1055 Budapest, Falk Miksa utca 9-11.</p>
          <p>Mailing address: 1363 Budapest, Pf. 9.</p>
          <p>
            Website:
            <a class="privacy-link" href="https://www.naih.hu" target="_blank" rel="noreferrer">www.naih.hu</a>
          </p>
        </div>
        <div class="privacy-subsection">
          <h3>2. Bring a court action</h3>
          <p>
            The data subject may bring an action before the court having jurisdiction over their place of residence or
            stay.
          </p>
        </div>
      </section>

      <section class="privacy-section">
        <div class="privacy-section-title">
          <span class="privacy-section-number">9.</span>
          <h2>Changes to this notice</h2>
        </div>
        <p>
          We reserve the right to modify this Privacy Policy in the event of legal or technological changes. The
          current version is always available on the website.
        </p>
        <p><br /><strong>Effective from:</strong> 2 March 2026 until withdrawn.</p>
        <div class="privacy-footer text-center">
          <p><br /><strong>Last updated:</strong> 2 March 2026.</p>
        </div>
      </section>
    </div>
  `,
};

export default privacyPolicyEn;
